// <auto-generated />
using System;
using Application.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Application.Models.CriticalityIndex", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int8")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Activities")
                        .HasColumnType("varchar")
                        .HasColumnName("Activities");

                    b.Property<string>("AvailabilityOfRepairPersonnel")
                        .HasColumnType("varchar")
                        .HasColumnName("AvailabilityOfRepairPersonnel");

                    b.Property<string>("AvailabilityOfRequiredParts")
                        .HasColumnType("varchar")
                        .HasColumnName("AvailabilityOfRequiredParts");

                    b.Property<string>("AverageRepairTime")
                        .HasColumnType("varchar")
                        .HasColumnName("AverageRepairTime");

                    b.Property<string>("Corrective")
                        .HasColumnType("varchar")
                        .HasColumnName("Corrective");

                    b.Property<string>("CostsManagement")
                        .HasColumnType("varchar")
                        .HasColumnName("CostsManagement");

                    b.Property<string>("CriticalityIndexValue")
                        .HasColumnType("varchar")
                        .HasColumnName("CriticalityIndexValue");

                    b.Property<string>("ElectricityExpensives")
                        .HasColumnType("varchar")
                        .HasColumnName("ElectricityExpensives");

                    b.Property<string>("EnergyGeneration")
                        .HasColumnType("varchar")
                        .HasColumnName("EnergyGeneration");

                    b.Property<string>("EnergyUse")
                        .HasColumnType("varchar")
                        .HasColumnName("EnergyUse");

                    b.Property<string>("EnvironmentalQuality")
                        .HasColumnType("varchar")
                        .HasColumnName("EnvironmentalQuality");

                    b.Property<string>("EnvironmentalRisks")
                        .HasColumnType("varchar")
                        .HasColumnName("EnvironmentalRisks");

                    b.Property<string>("Governance")
                        .HasColumnType("varchar")
                        .HasColumnName("Governance");

                    b.Property<string>("IndustrialManagement")
                        .HasColumnType("varchar")
                        .HasColumnName("IndustrialManagement");

                    b.Property<string>("IndustrialSector")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("IndustrialSector");

                    b.Property<string>("IndustryName")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("IndustryName");

                    b.Property<string>("Instrumentation")
                        .HasColumnType("varchar")
                        .HasColumnName("Instrumentation");

                    b.Property<string>("Investiments")
                        .HasColumnType("varchar")
                        .HasColumnName("Investiments");

                    b.Property<string>("Maintenance")
                        .HasColumnType("varchar")
                        .HasColumnName("Maintenance");

                    b.Property<string>("ManagementStrategy")
                        .HasColumnType("varchar")
                        .HasColumnName("ManagementStrategy");

                    b.Property<string>("MeanTimeBetweenFailures")
                        .HasColumnType("varchar")
                        .HasColumnName("MeanTimeBetweenFailures");

                    b.Property<string>("No_Renewable")
                        .HasColumnType("varchar")
                        .HasColumnName("No_Renewable");

                    b.Property<string>("OperationSensitivity")
                        .HasColumnType("varchar")
                        .HasColumnName("OperationSensitivity");

                    b.Property<string>("Operation_Work")
                        .HasColumnType("varchar")
                        .HasColumnName("Operation_Work");

                    b.Property<string>("Predictive")
                        .HasColumnType("varchar")
                        .HasColumnName("Predictive");

                    b.Property<string>("PredictiveOperation")
                        .HasColumnType("varchar")
                        .HasColumnName("PredictiveOperation");

                    b.Property<string>("Preventive")
                        .HasColumnType("varchar")
                        .HasColumnName("Preventive");

                    b.Property<string>("Process")
                        .HasColumnType("varchar")
                        .HasColumnName("Process");

                    b.Property<string>("Renewable")
                        .HasColumnType("varchar")
                        .HasColumnName("Renewable");

                    b.Property<string>("SkillLevels")
                        .HasColumnType("varchar")
                        .HasColumnName("SkillLevels");

                    b.Property<string>("Solubility")
                        .HasColumnType("varchar")
                        .HasColumnName("Solubility");

                    b.Property<string>("Technology")
                        .HasColumnType("varchar")
                        .HasColumnName("Technology");

                    b.Property<string>("TechnologyDataCollection")
                        .HasColumnType("varchar")
                        .HasColumnName("TechnologyDataCollection");

                    b.Property<string>("Toxicity")
                        .HasColumnType("varchar")
                        .HasColumnName("Toxicity");

                    b.Property<DateTime>("Ultima_Atualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("Ultima_Atualizacao")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("WorkLoad")
                        .HasColumnType("varchar")
                        .HasColumnName("WorkLoad");

                    b.HasKey("Id")
                        .HasName("pk_criticalityIndex");

                    b.ToTable("CriticalityIndex", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
